(function initializeEffects() {
  'use strict';
  const client = window.supabaseClient;
  const button = document.getElementById('effects-register'); const modal = document.getElementById('effects-form-modal'); const form = document.getElementById('effects-form'); const list = document.getElementById('effects-list'); const status = document.getElementById('effects-status'); const message = document.getElementById('effects-message');
  let userId = null; let editingId = null;
  const today = () => new Date().toISOString().slice(0, 10); const date = (value) => { const [year, month, day] = String(value).split('-'); return `${day}/${month}/${year}`; };
  const toast = (text, type = 'info') => window.showToast?.(text, type);
  function open(record = null) { editingId = record?.id || null; form.reset(); form.elements.record_date.value = record?.record_date || today(); form.elements.note.value = record?.note || ''; message.hidden = true; modal.hidden = false; document.body.classList.add('auth-modal-open'); }
  function close() { modal.hidden = true; editingId = null; document.body.classList.remove('auth-modal-open'); }
  function render(rows) { list.replaceChildren(); if (!rows.length) { status.hidden = false; status.textContent = 'Você ainda não registrou anotações.'; return; } status.hidden = true; rows.forEach((record) => { const item = document.createElement('article'); item.className = 'measurements-card'; const heading = document.createElement('strong'); heading.textContent = date(record.record_date); const note = document.createElement('p'); note.textContent = record.note; const actions = document.createElement('div'); actions.className = 'measurements-actions'; const edit = document.createElement('button'); edit.type = 'button'; edit.className = 'weight-action edit'; edit.textContent = 'Editar'; edit.addEventListener('click', () => open(record)); const remove = document.createElement('button'); remove.type = 'button'; remove.className = 'weight-action delete'; remove.textContent = 'Excluir'; remove.addEventListener('click', async () => { if (!window.confirm('Excluir esta anotação?')) return; const { error } = await client.from('application_effect_notes').delete().eq('id', record.id); if (error) return toast('Não foi possível excluir a anotação.', 'error'); load(); }); actions.append(edit, remove); item.append(heading, note, actions); list.append(item); }); }
  async function load() { if (!userId) return; status.hidden = false; status.textContent = 'Carregando anotações...'; const { data, error } = await client.from('application_effect_notes').select('id,record_date,note,created_at').order('record_date', { ascending: false }).order('created_at', { ascending: false }); if (error) { status.textContent = 'Não foi possível carregar as anotações.'; return; } render(data || []); }
  button.addEventListener('click', () => open()); document.querySelectorAll('[data-effects-close]').forEach((node) => node.addEventListener('click', close)); document.addEventListener('keydown', (event) => { if (event.key === 'Escape' && !modal.hidden) { event.preventDefault(); close(); } }); form.addEventListener('submit', async (event) => { event.preventDefault(); const note = form.elements.note.value.trim(); if (!note || note.length > 1000) { message.textContent = 'Informe uma anotação de até 1000 caracteres.'; message.hidden = false; return; } const payload = { record_date: form.elements.record_date.value, note }; const recordId = editingId; let result; try { result = recordId ? await client.from('application_effect_notes').update(payload).eq('id', recordId) : await client.from('application_effect_notes').insert({ ...payload, user_id: userId }); } catch (error) { result = { error }; } if (result.error) { message.textContent = 'Não foi possível salvar a anotação.'; message.hidden = false; return; } close(); await load(); toast('Anotação salva.', 'success'); });
  if (!client) return; client.auth.onAuthStateChange((_event, session) => { userId = session?.user?.id || null; if (userId) load(); else { list.replaceChildren(); status.textContent = ''; } });
}());
